### PR TITLE
Feature/multiple account

### PR DESCRIPTION
**Pull request by nbaulesglobalsolutions**

### CODE REVIEW

**Comment by dabura667** [comment]
Would be nice if you could type in an index number instead of clicking next and previous buttons...

**Comment by angerman** [comment]
@btchip why was this closed?

**Comment by btchip** [comment]
Because it was just someome resubmitting one development branch we already had

**Comment by angerman** [comment]
@btchip, thanks! Is there any info regarding multiple account support? Is there a list of open issues that branch still has and that would need to be fixed for it to get merged?

**Comment by btchip** [comment]
We plan to support it on our next generation application suite - no new features are implemented on this one

**Comment by angerman** [comment]
@btchip, is that publicly available somewhere already or is there somr info regarding the next gen app suite you could share a link to?

**Comment by btchip** [comment]
It'll be available early 2018

**Comment by angerman** [comment]
@btchip, thanks!

**Pull request closed without merging**
